### ISSUE TITLE
error installing from source on `osx`

### ISSUE THREAD

**Issue by gretel** [terlar/fry#44]
```
$ uname -a
Darwin host.local 15.5.0 Darwin Kernel Version 15.5.0: Fri Apr 22 18:59:34 PDT 2016; root:xnu-3248.50.21~19/RELEASE_X86_64 x86_64
$ make
install -D -m644 man/man1/fry.1 "/usr/share/man/man1/fry.1"
install: illegal option -- D
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
make: *** [install] Error 64
```

works when the `-D` flag is removed, guess it's not `POSIX`. additionally, `sudo` is required to have it installed.

**Comment by terlar** [comment]
I will look into the issue with the `-D` flag will have to find some common ways of the install command between BSD and GNU version.

What do you mean about `sudo`? Should not be required, are you talking about `script/bootstrap.sh`? That is only for usage in vagrant / travis CI.

**Comment by terlar** [comment]
Or you mean about the location of the installation in the Makefile? In that case an option is to set DESTDIR and install to "whatever" location you wish.

**Comment by gretel** [comment]
@terlar sorry, yes i am referring to the `DESTDIR` which could be somewhere user writable on `OSX`. that brings up the question where that'd be without detecting if somebody has `homebrew` installed - kinda circular considerung a `brew` is available.

**Comment by terlar** [comment]
Yeah, that is kind of user specific and if you want to do that you manually have to add those completion paths, function paths and conf d to fish.

The thought for this is to utilize the vendor folders specified by fish which will be in the same location you installed your fish. So if you have installed fish in `/usr/local` like most `homebrew` installations does, then you would also want this to end up there.

However that is a bit different, if you have `/usr/local` writable by your user or are using `sudo` and want it to end up in that location you have to specify `PREFIX` instead of `DESTDIR`.

So then it would be `make install PREFIX=/usr/local`. It is not possible to use DESTDIR for that since `DESTDIR` will go before `PREFIX` and `PREFIX` by default is configured to `/usr` in the Makefile.

So you have two options to affect the destination of the installation, either change `DESTDIR` or `PREFIX`.

Does this work out for you? Some people on linux have a local usr tree under their home directory, but then again you would have to do some manual changes to get this working. So recommended way is to in some way install it in the same path that fish was installed.

**Comment by gretel** [comment]
@terlar yup, thanks for depth. best thing me can think of having'd be a `fishfile` and let [`fisherman`](https://github.com/fisherman/fisherman) manage the installation. please join us on slack if you have the slighest question. regards

**Comment by terlar** [comment]
I will look into how to do this, always good to have options.

**Comment by gretel** [comment]
initially i was missing the documentation because it's so darn simple 😝 . check the *FAQ* part of the [`README`](https://github.com/fisherman/fisherman/blob/master/README.md) please.

**Comment by terlar** [comment]
So looking into this seems like there is nothing todo, it just works.

Try: `fisher install terlar/fry`. That worked for me. Let me know if there is some issues...
